// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go

// Package workers is a generated GoMock package.
package workers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// SendDeletionRequestToWorker mocks base method.
func (m *MockWorker) SendDeletionRequestToWorker(req DeletionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeletionRequestToWorker", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeletionRequestToWorker indicates an expected call of SendDeletionRequestToWorker.
func (mr *MockWorkerMockRecorder) SendDeletionRequestToWorker(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeletionRequestToWorker", reflect.TypeOf((*MockWorker)(nil).SendDeletionRequestToWorker), req)
}
